### ISSUE TITLE
kubectl proxy does not support WebSocket protocol

### ISSUE THREAD

**Issue by dex4er** [freelensapp/freelens-k8s-proxy#2]
Starting port-forward with kubectl 1.31.0 and Kubernetes 1.31.0 cluster ends with error:

<img width="511" alt="image" src="https://github.com/user-attachments/assets/10ee4550-b67c-489c-bf94-d7e5a800e377">

Most likely because this version uses WebSocket protocol and freelens-k8s-proxy does not bypass it.

Recompiling it with the current libraries would probably help.

**Comment by dex4er** [comment]
Actually it might be caused that Freelens doesn't use kubectl that matches version from the cluster. As I checked with extra debugging it uses `/Users/dex4er/Sources/freelens/freelens/binaries/client/darwin/arm64/kubectl` (the default binary) rather than something from `~/Library/Application\ Support/FreelensDev/binaries`

**Comment by robertobandini** [comment]
> Actually it might be caused that Freelens doesn't use kubectl that matches version from the cluster. As I checked with extra debugging it uses `/Users/dex4er/Sources/freelens/freelens/binaries/client/darwin/arm64/kubectl` (the default binary) rather than something from `~/Library/Application\ Support/FreelensDev/binaries`

You mean only when you try to do the port forward action?
I think I saw that error many other times before, but I've never checked maybe also cause it doesn't appears every time.
Anyway of course I agree to check it and resolve it.

**Comment by dex4er** [comment]
I'm closing this error in favour of https://github.com/freelensapp/freelens/issues/32
